xing_xing_map = {
    "1":"太阳",
    "2":"月亮",
    "3":"水星",
    "4":"金星",
    "5":"火星",
    "6":"木星",
    "7":"土星",
    "8":"天王星",
    "9":"海王星",
    "10":"冥王星"
}
xing_xing_py_map = {
    "1":"taiyang",
    "2":"yueliang",
    "3":"shuixing",
    "4":"jinxing",
    "5":"huoxing",
    "6":"muxing",
    "7":"tuxing",
    "8":"tianwangxing",
    "9":"haiwangxing",
    "10":"mingwangxing"
}
shi_er_gong = {
    "1": "第一宫",
    "2": "第二宫",
    "3": "第三宫",
    "4": "第四宫",
    "5": "第五宫",
    "6": "第六宫",
    "7": "第七宫",
    "8": "第八宫",
    "9": "第九宫",
    "10": "第十宫",
    "11": "第十一宫",
    "12": "第十二宫",
}
xing_zuo = {
    "1": "baiyang",
    "2": "jinniu",
    "3": "shuangzi",
    "4": "juxie",
    "5": "shizi",
    "6": "chunv",
    "7": "tiancheng",
    "8": "tianxie",
    "9": "sheshou",
    "10": "mojie",
    "11": "shuiping",
    "12": "shuangyu",
}
_xing_image_map = {
    "太阳": "https://images.swft.pro/astroAI/planet/taiyang.png",
    "月亮": "https://images.swft.pro/astroAI/planet/yueliang.png",
    "水星": "https://images.swft.pro/astroAI/planet/shuixing.png",
    "金星": "https://images.swft.pro/astroAI/planet/jinxing.png",
    "火星": "https://images.swft.pro/astroAI/planet/huoxing.png",
    "木星": "https://images.swft.pro/astroAI/planet/muxing.png",
    "土星": "https://images.swft.pro/astroAI/planet/tuxing.png",
    "天王星": "https://images.swft.pro/astroAI/planet/tianwangxing.png",
    "海王星": "https://images.swft.pro/astroAI/planet/haiwangxing.png",
    "冥王星": "https://images.swft.pro/astroAI/planet/mingwangxing.png",
    "上升点": "https://images.swft.pro/astroAI/planet/Asc.png",
    "天顶": "https://images.swft.pro/astroAI/planet/MC.png"
}
_xing_image_yellow_map = {
    "太阳": "https://images.swft.pro/astroAI/planet/taiyang-yellow.png",
    "月亮": "https://images.swft.pro/astroAI/planet/yueliang-yellow.png",
    "水星": "https://images.swft.pro/astroAI/planet/shuixing-yellow.png",
    "金星": "https://images.swft.pro/astroAI/planet/jinxing-yellow.png",
    "火星": "https://images.swft.pro/astroAI/planet/huoxing-yellow.png",
    "木星": "https://images.swft.pro/astroAI/planet/muxing-yellow.png",
    "土星": "https://images.swft.pro/astroAI/planet/tuxing-yellow.png",
    "天王星": "https://images.swft.pro/astroAI/planet/tianwangxing-yellow.png",
    "海王星": "https://images.swft.pro/astroAI/planet/haiwangxing-yellow.png",
    "冥王星": "https://images.swft.pro/astroAI/planet/mingwangxing-yellow.png",
    "上升点": "https://images.swft.pro/astroAI/planet/Asc-yellow.png",
    "天顶": "https://images.swft.pro/astroAI/planet/MC-yellow.png"
}

nong_li_month = {
    '1': '一月',
    '2': '二月',
    '3': '三月',
    '4': '四月',
    '5': '五月',
    '6': '六月',
    '7': '七月',
    '8': '八月',
    '9': '九月',
    '10': '十月',
    '11': '十一月',
    '12': '十二月',
}
nong_li_day = {
    '1': '初一',
    '2': '初二',
    '3': '初三',
    '4': '初四',
    '5': '初五',
    '6': '初六',
    '7': '初七',
    '8': '初八',
    '9': '初九',
    '10': '初十',
    '11': '十一',
    '12': '十二',
    '13': '十三',
    '14': '十四',
    '15': '十五',
    '16': '十六',
    '17': '十七',
    '18': '十八',
    '19': '十九',
    '20': '二十',
    '21': '廿一',
    '22': '廿二',
    '23': '廿三',
    '24': '廿四',
    '25': '廿五',
    '26': '廿六',
    '27': '廿七',
    '28': '廿八',
    '29': '廿九',
    '30': '三十',
}